
- name: Create first instance
  hosts: instance_type_t2_small
  gather_facts: False
  vars:
    keypair: mykeypair2
    security_group: mySecurityGroup
    image: ami-00399ec92321828f5
    region: us-east-2
    object: /myapps/hello-1.0.war.tar.gz
    bucket: mybucket1.com
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: t2.small
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        assign_public_ip: yes
      register: ec2
    - name: Ensure maven-package is present
      apt:
        name: maven
        state: present
    - name: Ensure project is present
      copy:
        src: /home/boxfuse-sample-java-war-hello/
        dest: /root

    - name: Ensure maven service is started
      shell: "mvn clean package"
    - name: Ensure project is packaged
      shell: "ls /root/target"
    - name: Create a tar.gz archive of a single file
      archive:
        path: /root/target/hello-1.0.war
        dest: /root/target/hello-1.0.war.tar.gz
        format: gz
    - name: PUT operation
      aws_s3:
        bucket: "{{ bucket }}"
        object: "{{ object }}"
          src: /root/target/hello-1.0.war.tar.gz
          mode: put

- name: Create second instance
  hosts: instance_type_t2_medium
  gather_facts: True
  vars:
    keypair: "{{ keypair }}"
    security_group: "{{ security_group }}"
    image: ami-00399ec92321828f5
    region:
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: t2.medium
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        assign_public_ip: yes
      register: ec2

    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present
    - name: GET operation
      aws_s3:
        bucket: "{{ bucket }}"
        object: "{{ object }}"
        dest: /home/usr/
        mode: get
    - name: Unarchive a single file
      unarchive:
        path: /home/usr/hello-1.0.war.tar.gz
        dest: /home/usr/hello-1.0.war
    - name: Ensure project is present
      copy:
        src: /home/usr/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started


- name: Terminate instances
  hosts: [builder, runner]
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        group_name: "{{ security_group }}"
